#!/usr/bin/env python
import rospy
from std_msgs.msg import String

def talker():
    pub1 = rospy.Publisher('kp', String, queue_size=10)
    pub2 = rospy.Publisher('kd', String, queue_size=10)
    pub3 = rospy.Publisher('err', String, queue_size=10)
    rospy.init_node('line_follow', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        kp=2
	kd=3
	err=1
        rospy.loginfo(kp)
        pub1.publish(kp)
	pub2.publish(kd)
	pub3.publish(err)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
